name: 'dbt_dskola_project'
version: '1.0'
config-version: 2

profile: 'dbt_dskola_project'

# These specify where dbt will look for different types of files.
source-paths: ["models"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
data-paths: ["data"]
snapshot-paths: ["snapshots"]

# Configuring paths for documentation and tests
test-paths: ["tests"]
docs-paths: ["docs"]

# Configuring target paths for manifest and run results
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Defining models configuration
models:
  dbt_dskola_project:
    # Default configurations for all models
    materialized: table
    # staging:
    #   +schema: raw_data
    #   +materialized: table
    # warehouse:
    #   +schema: data_warehouse
    #   +materialized: table
    # marts:
    #   +schema: data_mart
    #   +materialized: table

# Defining seeds configuration
seeds:
  dbt_dskola_project:
    +schema: seeds

# Defining snapshots configuration
snapshots:
  dbt_dskola_project:
    +schema: snapshots

# Defining sources configuration
# sources:
#   dbt_dskola_project:
#     staging:
#       customers:
#         - +enabled: true
#       orders:
#         - +enabled: true
#       payments:
#         - +enabled: true
#       products:
#         - +enabled: true

# Configuring packages
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6

# Configuring on-run-start and on-run-end hooks
on-run-start: []
on-run-end: []

# Configuring vars
vars: {}