version: 2

sources:
  - name: raw_categories
  - name: raw_customers
  - name: raw_employee_territories
  - name: raw_employees
  - name: raw_order_details
  - name: raw_orders
  - name: raw_products
  - name: raw_regions
  - name: raw_shippers
  - name: raw_suppliers
  - name: raw_territories

models:
  - name: raw_categories
    description: "Staging model for raw_categories"
    tests:
      - not_null:
          - categoriesID
          - categoryName
          
  - name: raw_customers
    description: "Staging model for raw_customers"
    tests:
      - not_null:
          - customerID
          - companyName
           
  - name: raw_employee_territories
    description: "Staging model for raw_employee_territories"
    tests:
      - not_null:
          - employeeID
          - territoryID
          
          
    - name: raw_employees
    description: "Staging model for raw_employees"
    tests:
      - not_null:
          - employeeID
          
          
    - name: raw_order_details
    description: "Staging model for raw_order_details"
    tests:
      - not_null:
          - orderID
          - productID
          
    - name: raw_orders
    description: "Staging model for raw_orders"
    tests:
      - not_null:
          - orderID
          - customerID
          - employeeID
          
    - name: raw_products
    description: "Staging model for raw_products"
    tests:
      - not_null:
          - productID
          - productName
          
    - name: raw_regions
    description: "Staging model for raw_regions"
    tests:
      - not_null:
          - regionID
          - regionDescription
          
          
    - name: raw_shippers
    description: "Staging model for raw_shippers"
    tests:
      - not_null:
          - shipperID
          
    - name: raw_suppliers
    description: "Staging model for raw_suppliers"
    tests:
      - not_null:
          - supplierID


  - name: raw_territories
    description: "Staging model for raw_territories"
    tests:
      - not_null:
          - territoryID
